name: Actualizar KML Diario

on:
  schedule:
    # Se ejecuta todos los días a las 05:00 UTC (07:00 hora de España)
    - cron: '0 5 * * *'
  workflow_dispatch: # Permite ejecutarlo manualmente cuando quieras

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar el código
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Ejecutar script de generación KML
        run: python generar_kml.py

      - name: Guardar y subir cambios en el KML
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add mercadillos_valencia.kml
          git commit -m "Auto-actualización KML" || exit 0
          git push
